### ISSUE TITLE
Error: growth_locked

### ISSUE THREAD

**Issue by S1mp1yDucky** [mouricedevs/gifted#84]
It's not working

![image](https://github.com/user-attachments/assets/26d15eca-c874-4729-9e8b-afc864f20aa5)

Also can we please change the title and channel?

It shows gifted-md at the very top
and a whatsapp community at "view channel"

![image](https://github.com/user-attachments/assets/a836bba5-e46d-4b4a-b78e-8b8b9905fe7b)

**Comment by mouricedevs** [comment]
Okay
